import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/components/authProvider";
import { UserProvider } from "@/context/userContext";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark:bg-darkTheme overflow-x-hidden`}
      >
        <UserProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </UserProvider>
      </body>
    </html>
  );
}
